-- Create a table for leads
create table leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  phone text not null,
  message text not null,
  status text default 'New'::text
);

-- Set up Row Level Security (RLS)
-- For now, we enable read access for everyone (or authenticated users) 
-- and insert access for everyone (public leads form).
alter table leads enable row level security;

create policy "Enable insert for public" on leads for insert with check (true);
create policy "Enable read access for authenticated users only" on leads for select using (auth.role() = 'authenticated');
