-- Versão "Prova de Falhas" do Schema
-- Este script verifica se as tabelas já existem antes de criar.
-- Também recria as permissões para garantir que estão corretas.

-- 1. Agenda de Consultorias
create table if not exists consulting_jobs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  client text not null,
  description text,
  start_date date not null,
  end_date date,
  status text default 'Agendado'::text
);

-- 2. Receitas Trefila
create table if not exists trefila_recipes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  date text,
  entry numeric not null,
  exit numeric not null,
  passes integer not null,
  dies jsonb not null
);

-- 3. Treliças
create table if not exists trusses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  model text not null,
  height numeric not null,
  length numeric not null,
  top_diam numeric not null,
  bot_diam numeric not null,
  sine_diam numeric not null,
  total_weight numeric not null
);

-- 4. Orçamentos
create table if not exists saved_quotes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  client_name text not null,
  contact text,
  start_date date,
  weeks integer,
  value_weekly_service numeric,
  value_weekly_travel numeric,
  value_weekly_food numeric,
  shifts text,
  hours_per_day numeric,
  working_days jsonb,
  tax_percent numeric
);

-- 5. Configurar Permissões (Dropa antigas para evitar erro de duplicação)

-- Consulting Jobs
alter table consulting_jobs enable row level security;
drop policy if exists "Enable all access for public" on consulting_jobs;
create policy "Enable all access for public" on consulting_jobs for all using (true) with check (true);

-- Trefila
alter table trefila_recipes enable row level security;
drop policy if exists "Enable all access for public" on trefila_recipes;
create policy "Enable all access for public" on trefila_recipes for all using (true) with check (true);

-- Trusses
alter table trusses enable row level security;
drop policy if exists "Enable all access for public" on trusses;
create policy "Enable all access for public" on trusses for all using (true) with check (true);

-- Quotes
alter table saved_quotes enable row level security;
drop policy if exists "Enable all access for public" on saved_quotes;
create policy "Enable all access for public" on saved_quotes for all using (true) with check (true);
