-- Create table for Consulting Jobs (Agenda)
create table consulting_jobs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  client text not null,
  description text,
  start_date date not null,
  end_date date,
  status text default 'Agendado'::text
);

-- Create table for Trefila Recipes
create table trefila_recipes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  date text,
  entry numeric not null,
  exit numeric not null,
  passes integer not null,
  dies jsonb not null -- Stores the array of die sizes
);

-- Create table for Saved Trusses (Treliças)
create table trusses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  model text not null,
  height numeric not null,
  length numeric not null,
  top_diam numeric not null,
  bot_diam numeric not null,
  sine_diam numeric not null,
  total_weight numeric not null
);

-- Create table for Saved Quotes (Orçamentos)
create table saved_quotes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  client_name text not null,
  contact text,
  start_date date,
  weeks integer,
  value_weekly_service numeric,
  value_weekly_travel numeric,
  value_weekly_food numeric,
  shifts text,
  hours_per_day numeric,
  working_days jsonb, -- Stores array of numbers [1,2,3...]
  tax_percent numeric
);

-- Enable RLS for all tables
alter table consulting_jobs enable row level security;
alter table trefila_recipes enable row level security;
alter table trusses enable row level security;
alter table saved_quotes enable row level security;

-- Policies (Public Insert/Select for now as per previous 'leads' setup, or Authenticated)
-- Assuming the user is using the app as 'gestor' but maybe not fully authenticated via Supabase Auth UI yet.
-- Using 'anon' policies for simplicity to match previous 'leads' setup if needed, or 'authenticated' if they log in.

-- Consulting Jobs policies
create policy "Enable all access for public" on consulting_jobs for all using (true) with check (true);

-- Trefila Recipes policies
create policy "Enable all access for public" on trefila_recipes for all using (true) with check (true);

-- Trusses policies
create policy "Enable all access for public" on trusses for all using (true) with check (true);

-- Saved Quotes policies
create policy "Enable all access for public" on saved_quotes for all using (true) with check (true);
