-- Criar tabela para Malhas (Meshes)
create table meshes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  tela text not null,
  metros numeric not null,
  bitola numeric not null,
  espacamento text,
  dimensao text,
  t numeric,
  l numeric,
  peso numeric not null
);

-- Criar tabela para Empresas (Comissões)
create table companies (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  percent numeric default 5
);

-- Criar tabela para Entradas de Comissão (Valores Mensais)
create table commission_entries (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  company_id bigint references companies(id) on delete cascade,
  month_index integer not null, -- 0 a 11
  value numeric default 0,
  unique(company_id, month_index) -- previne duplicatas para o mesmo mês/empresa
);

-- Criar tabela para Registros Financeiros (Adiantamentos/Recebimentos)
create table financial_records (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  type text not null check (type in ('advance', 'receipt')),
  value numeric not null,
  company_name text not null -- Armazenando o nome diretamente como no app atual
);

-- Habilitar RLS (Segurança em Nível de Linha)
alter table meshes enable row level security;
alter table companies enable row level security;
alter table commission_entries enable row level security;
alter table financial_records enable row level security;

-- Criar políticas (Acesso público para simplicidade conforme solicitado)
create policy "Enable all access for public" on meshes for all using (true) with check (true);
create policy "Enable all access for public" on companies for all using (true) with check (true);
create policy "Enable all access for public" on commission_entries for all using (true) with check (true);
create policy "Enable all access for public" on financial_records for all using (true) with check (true);
